### ISSUE TITLE
Does this repo apply to the pitts dataset

### ISSUE THREAD

**Issue by DonMuv** [jomariya23156/SuperGlue-for-Visual-Place-Recognition#1]
Hi,
Does this repo apply to the pittsburgh dataset, and how to use your code with the pittsburgh dataset
thank you

**Comment by jomariya23156** [comment]
Yes, of course. This repo can apply to any dataset as long as you can save all images in 1 directory (if there are more than 1 directory or you have other ways to retrieve the image from other sources, you have to tweak the code a bit). There are 2 ways to accomplish this with the codes in this repo. Let's say you have all pittsburgh images in a directory name `pittsburgh`,  
1)  `python superglue_rank_images.py -q 60.png -i pittsburgh -o rank_output/rank_output_pittsburgh_images --resize 320 240 --resize_float --viz --viz_extension png --fast_viz --show_keypoint`. *Note* that `60.png` should be the name of the query image and it must be stored in the same directory. If you want something simple, using this command is just fine.  
Doing it this way will do everything from images to ranking, but to use it in the real-world application, it's kinda slow. So, another way to make it faster is to extract and save the SuperPoint of all images in database beforehand, then after receiving the new query image, extract the SuperPoint from that image and compare to all SuperPoint in the database. (follow the second option to do this)  
2) First, extract the SuperPoint from all images and save it in database (in this case, the output directory) using `python superpoints_from_images.py --input_dir pittsburgh --output_dir saved_superpoints/pickle/pittsburgh --resize 320 240 --cuda`. Then `python superglue_rank_superpoints_file.py -q 60.pickle -i saved_superpoints/pickle/pittsburgh -o rank_output/rank_output_pittsburgh --image_size 320 240 --cuda`. *Note*: This file, `superglue_rank_superpoints_file.py`, does not support inputting image from the outside directory. If you wish to do so, use API which is also provided in this repo. And if you want to do visualization, you can use `python ranking_viz.py -q 60.png -i rank_output/rank_output_pittsburgh/ranking_score.csv -id pittsburgh --input_extension png --output_extension png -r 10` *Note*: you must change input_extension to match your input image and you can choose any output_extension as you wish.  
  
Read the README for more detail. I've described everything there.

**Comment by jomariya23156** [comment]
Since it seemed like this issue is now inactive. I'm gonna close it for now.
